srcdir = "."
blddir = "build"

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")
  conf.find_program('node', var='NODE', mandatory=True)
  conf.check_cfg(package='libvirt', args='--cflags --libs', atleast_version='0.8.1')

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon")
  obj.target = "node-libvirt"
  obj.source = bld.path.ant_glob('**/*.cc')
  obj.uselib = "LIBVIRT"

